/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    Tip: typeof import('./src/components/Tip.vue')['default']
    UsersForm: typeof import('./src/components/UsersForm.vue')['default']
    UsersTable: typeof import('./src/components/UsersTable.vue')['default']
    UsersTableHeader: typeof import('./src/components/UsersTableHeader.vue')['default']
    UsersTableRow: typeof import('./src/components/UsersTableRow.vue')['default']
  }
}
